- name: Clear default keystore values
  become: true
  ansible.builtin.command: "/usr/share/elasticsearch/bin/elasticsearch-keystore remove {{ item }}"
  loop:
    - xpack.security.http.ssl.keystore.secure_password
    - xpack.security.transport.ssl.keystore.secure_password
    - xpack.security.transport.ssl.truststore.secure_password
  failed_when: false


- name: Add new keystore values for custom certs
  become: true
  ansible.builtin.shell: "echo {{ elastic_transport_pass }} | \
                            /usr/share/elasticsearch/bin/elasticsearch-keystore add {{ item }} -x"
  loop:
    - xpack.security.transport.ssl.keystore.secure_password
    - xpack.security.transport.ssl.truststore.secure_password
