- name: Configure elasticsearch.yml
  become: true
  ansible.builtin.template:
    src: ./templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: u+rw,g+rw
  notify: Make sure elasticsearch is started
